-- MySQL Script generated by MySQL Workbench
-- Fri Jan 22 19:17:33 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `test` ;

-- -----------------------------------------------------
-- Table `test`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`user` (
  `id` BIGINT NOT NULL,
  `firstName` VARCHAR(50) NULL DEFAULT NULL,
  `middleName` VARCHAR(50) NULL DEFAULT NULL,
  `lastName` VARCHAR(50) NULL DEFAULT NULL,
  `mobile` VARCHAR(15) NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `passwordHash` VARCHAR(32) NOT NULL,
  `admin` TINYINT(1) NOT NULL,
  `vendor` TINYINT(1) NOT NULL,
  `registeredAt` DATETIME NOT NULL,
  `lastLogin` DATETIME NULL DEFAULT NULL,
  `intro` TINYTEXT NULL DEFAULT NULL,
  `profile` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `test`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`cart` (
  `id` BIGINT NOT NULL,
  `userId` BIGINT NULL DEFAULT NULL,
  `sessionId` VARCHAR(100) NOT NULL,
  `token` VARCHAR(100) NOT NULL,
  `status` SMALLINT NOT NULL,
  `firstName` VARCHAR(50) NULL DEFAULT NULL,
  `middleName` VARCHAR(50) NULL DEFAULT NULL,
  `lastName` VARCHAR(50) NULL DEFAULT NULL,
  `mobile` VARCHAR(15) NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `line1` VARCHAR(50) NULL DEFAULT NULL,
  `line2` VARCHAR(50) NULL DEFAULT NULL,
  `city` VARCHAR(50) NULL DEFAULT NULL,
  `provine` VARCHAR(50) NULL DEFAULT NULL,
  `country` VARCHAR(50) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `upadatedAt` DATETIME NULL DEFAULT NULL,
  `content` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `cart to user_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `cart to user`
    FOREIGN KEY (`userId`)
    REFERENCES `test`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `test`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`product` (
  `id` BIGINT NOT NULL,
  `userId` BIGINT NOT NULL,
  `title` VARCHAR(75) NOT NULL,
  `metaTitle` VARCHAR(100) NULL DEFAULT NULL,
  `slug` VARCHAR(100) NOT NULL,
  `summary` TINYTEXT NULL DEFAULT NULL,
  `type` SMALLINT NOT NULL,
  `sku` VARCHAR(100) NOT NULL,
  `price` FLOAT NOT NULL,
  `discount` FLOAT NOT NULL,
  `quantity` SMALLINT NOT NULL,
  `shop` TINYINT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NULL DEFAULT NULL,
  `publishedAt` DATETIME NULL DEFAULT NULL,
  `startsAt` DATETIME NULL DEFAULT NULL,
  `endsAt` DATETIME NULL DEFAULT NULL,
  `content` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `product to user_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `product to user`
    FOREIGN KEY (`userId`)
    REFERENCES `test`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `test`.`cart_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`cart_item` (
  `id` BIGINT NOT NULL,
  `productId` BIGINT NOT NULL,
  `cartId` BIGINT NOT NULL,
  `sku` VARCHAR(100) NOT NULL,
  `price` FLOAT NOT NULL,
  `dicount` FLOAT NOT NULL,
  `quantity` SMALLINT NOT NULL,
  `active` SMALLINT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NULL DEFAULT NULL,
  `content` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `cartitem to product_idx` (`productId` ASC) VISIBLE,
  INDEX `cartitem to cart_idx` (`cartId` ASC) VISIBLE,
  CONSTRAINT `cartitem to cart`
    FOREIGN KEY (`cartId`)
    REFERENCES `test`.`cart` (`id`),
  CONSTRAINT `cartitem to product`
    FOREIGN KEY (`productId`)
    REFERENCES `test`.`product` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `test`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`category` (
  `id` BIGINT NOT NULL,
  `parentId` BIGINT NULL DEFAULT NULL,
  `title` VARCHAR(75) NOT NULL,
  `metaTitle` VARCHAR(100) NULL DEFAULT NULL,
  `slug` VARCHAR(100) NOT NULL,
  `content` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `parentId_idx` (`parentId` ASC) VISIBLE,
  INDEX `parentId to own _idx` (`parentId` ASC) VISIBLE,
  CONSTRAINT `parentId to own `
    FOREIGN KEY (`parentId`)
    REFERENCES `test`.`category` (`parentId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `test`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`order` (
  `id` BIGINT NOT NULL,
  `userId` BIGINT NULL DEFAULT NULL,
  `sessionId` VARCHAR(100) NOT NULL,
  `token` VARCHAR(100) NOT NULL,
  `status` SMALLINT NOT NULL,
  `subTotal` FLOAT NOT NULL,
  `itemDiscount` FLOAT NOT NULL,
  `tax` FLOAT NOT NULL,
  `shipping` FLOAT NOT NULL,
  `total` FLOAT NOT NULL,
  `promo` VARCHAR(50) NULL DEFAULT NULL,
  `discount` FLOAT NOT NULL,
  `grandTotal` FLOAT NOT NULL,
  `firstName` VARCHAR(50) NULL DEFAULT NULL,
  `middleName` VARCHAR(50) NULL DEFAULT NULL,
  `lastName` VARCHAR(50) NULL DEFAULT NULL,
  `mobile` VARCHAR(15) NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `line1` VARCHAR(50) NULL DEFAULT NULL,
  `line2` VARCHAR(50) NULL DEFAULT NULL,
  `city` VARCHAR(50) NULL DEFAULT NULL,
  `province` VARCHAR(50) NULL DEFAULT NULL,
  `country` VARCHAR(50) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NULL DEFAULT NULL,
  `content` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `order to user_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `order to user`
    FOREIGN KEY (`userId`)
    REFERENCES `test`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `test`.`order_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`order_item` (
  `id` BIGINT NOT NULL,
  `productId` BIGINT NOT NULL,
  `orderId` BIGINT NOT NULL,
  `sku` VARCHAR(100) NOT NULL,
  `price` FLOAT NOT NULL,
  `discount` FLOAT NOT NULL,
  `quantity` SMALLINT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `ORDERITEM TO PRODUCT_idx` (`productId` ASC) VISIBLE,
  INDEX `orderitem to order_idx` (`orderId` ASC) VISIBLE,
  CONSTRAINT `orderitem to order`
    FOREIGN KEY (`orderId`)
    REFERENCES `test`.`order` (`id`),
  CONSTRAINT `ORDERITEM TO PRODUCT`
    FOREIGN KEY (`productId`)
    REFERENCES `test`.`product` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `test`.`product_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`product_category` (
  `productId` BIGINT NOT NULL,
  `categoryId` BIGINT NOT NULL,
  PRIMARY KEY (`productId`, `categoryId`),
  INDEX `userId_idx` (`categoryId` ASC) VISIBLE,
  CONSTRAINT `parentId`
    FOREIGN KEY (`productId`)
    REFERENCES `test`.`category` (`id`),
  CONSTRAINT `userId`
    FOREIGN KEY (`categoryId`)
    REFERENCES `test`.`product` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `test`.`product_meta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`product_meta` (
  `id` BIGINT NOT NULL,
  `productId` BIGINT NOT NULL,
  `key` VARCHAR(50) NOT NULL,
  `content` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `meto to product_idx` (`productId` ASC) VISIBLE,
  CONSTRAINT `meto to product`
    FOREIGN KEY (`productId`)
    REFERENCES `test`.`product` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `test`.`product_review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`product_review` (
  `id` BIGINT NOT NULL,
  `productId` BIGINT NOT NULL,
  `parentId` BIGINT NULL DEFAULT NULL,
  `title` VARCHAR(100) NOT NULL,
  `rating` SMALLINT NULL DEFAULT NULL,
  `published` TINYINT(1) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `publishedAt` DATETIME NULL DEFAULT NULL,
  `content` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `to product_idx` (`productId` ASC) VISIBLE,
  INDEX `to own_idx` (`parentId` ASC) VISIBLE,
  CONSTRAINT `to own`
    FOREIGN KEY (`parentId`)
    REFERENCES `test`.`product_review` (`id`),
  CONSTRAINT `to product`
    FOREIGN KEY (`productId`)
    REFERENCES `test`.`product` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `test`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`tag` (
  `id` BIGINT NOT NULL,
  `title` VARCHAR(75) NOT NULL,
  `metaTitle` VARCHAR(100) NULL DEFAULT NULL,
  `slug` VARCHAR(100) NOT NULL,
  `content` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `test`.`product_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`product_tag` (
  `productId` BIGINT NOT NULL,
  `tagId` BIGINT NOT NULL,
  PRIMARY KEY (`productId`, `tagId`),
  INDEX `product tag to tag_idx` (`tagId` ASC) VISIBLE,
  CONSTRAINT `product tag to product`
    FOREIGN KEY (`productId`)
    REFERENCES `test`.`product` (`id`),
  CONSTRAINT `product tag to tag`
    FOREIGN KEY (`tagId`)
    REFERENCES `test`.`tag` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `test`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`transaction` (
  `id` BIGINT NOT NULL,
  `userId` BIGINT NOT NULL,
  `orderId` BIGINT NOT NULL,
  `code` VARCHAR(100) NOT NULL,
  `type` SMALLINT NOT NULL,
  `mode` SMALLINT NOT NULL,
  `status` SMALLINT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NULL DEFAULT NULL,
  `content` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `transaction to user_idx` (`userId` ASC) VISIBLE,
  INDEX `transacction to order_idx` (`orderId` ASC) VISIBLE,
  CONSTRAINT `transacction to order`
    FOREIGN KEY (`orderId`)
    REFERENCES `test`.`order` (`id`),
  CONSTRAINT `transaction to user`
    FOREIGN KEY (`userId`)
    REFERENCES `test`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
